name: maven CI

on:

  push:
    branches:
      - master
      - develop
      - 'feat/**'
    paths:
      - 'plugins/quartz-scheduler/**'
      - '.github/workflows/plugin-ci.yml'

  pull_request:
    branches:
      - develop
      - 'feat/**'
    paths:
      - 'plugins/quartz-scheduler/**'
      - '.github/workflows/plugin-ci.yml'


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin:
          - quartz-scheduler

    steps:

    - name: ${{ github.event.repository.name }}
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: maven
        cache-dependency-path: pom.xml

    - name: Build with Maven
      run: mvn -B package --file plugins/${{ plugin }}/pom.xml

    - name: Archive generated JAR file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ plugin }}-compiled-jars
        path: plugins/${{ plugin }}/target/*.jar
